"""initial schema: users, customers, bookings, trips, audit_log

Revision ID: 0001
Revises:
Create Date: 2026-07-10

Hand-authored rather than autogenerated, since Alembic's autogenerate
doesn't reliably detect the need to CREATE EXTENSION postgis, and getting
the first spatial migration right by hand is worth the clarity. Future
migrations (adding columns, new tables) can use
`alembic revision --autogenerate` as normal — this file just establishes
the baseline.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    user_role = postgresql.ENUM(
        "admin", "dispatcher", "driver", name="user_role"
    )
    booking_status = postgresql.ENUM(
        "queued", "matched", "waiting", "cancelled", name="booking_status"
    )
    trip_status = postgresql.ENUM(
        "forming", "confirmed", "in_progress", "completed", "cancelled",
        name="trip_status",
    )
    # Note: these ENUM types are created automatically by op.create_table()
    # below, the first time a column uses them — no separate .create() call
    # needed (calling both causes "type already exists").

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(120), nullable=False),
        sa.Column("phone", sa.String(20), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("role", user_role, nullable=False, server_default="dispatcher"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
    )
    op.create_index("ix_users_phone", "users", ["phone"])

    op.create_table(
        "customers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(120), nullable=False),
        sa.Column("phone_encrypted", sa.String(255), nullable=False),
        sa.Column("phone_lookup_hash", sa.String(64), nullable=False, unique=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
    )
    op.create_index(
        "ix_customers_phone_lookup_hash", "customers", ["phone_lookup_hash"]
    )

    op.create_table(
        "trips",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
        sa.Column("vehicle_label", sa.String(50), nullable=True),
        sa.Column("status", trip_status, nullable=False, server_default="forming"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
    )

    op.create_table(
        "bookings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "customer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("customers.id"),
            nullable=False,
        ),
        sa.Column(
            "trip_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("trips.id"),
            nullable=True,
        ),
        sa.Column("pickup_address_encrypted", sa.String(255), nullable=False),
        sa.Column(
            "pickup_point",
            geoalchemy2.Geography(geometry_type="POINT", srid=4326),
            nullable=False,
        ),
        sa.Column("dropoff_address_encrypted", sa.String(255), nullable=False),
        sa.Column(
            "dropoff_point",
            geoalchemy2.Geography(geometry_type="POINT", srid=4326),
            nullable=False,
        ),
        sa.Column("is_private", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("price_vnd", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "status", booking_status, nullable=False, server_default="queued"
        ),
        sa.Column("stop_order", sa.Integer, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
    )
    # Spatial indexes — these are what make ST_DWithin proximity queries fast
    op.create_index(
        "ix_bookings_pickup_point",
        "bookings",
        ["pickup_point"],
        postgresql_using="gist",
    )
    op.create_index(
        "ix_bookings_dropoff_point",
        "bookings",
        ["dropoff_point"],
        postgresql_using="gist",
    )
    op.create_index("ix_bookings_status", "bookings", ["status"])

    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("target_type", sa.String(50), nullable=False),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now()
        ),
    )
    op.create_index("ix_audit_log_actor_user_id", "audit_log", ["actor_user_id"])
    op.create_index("ix_audit_log_target_id", "audit_log", ["target_id"])


def downgrade() -> None:
    op.drop_table("audit_log")
    op.drop_index("ix_bookings_dropoff_point", table_name="bookings")
    op.drop_index("ix_bookings_pickup_point", table_name="bookings")
    op.drop_table("bookings")
    op.drop_table("trips")
    op.drop_table("customers")
    op.drop_table("users")

    bind = op.get_bind()
    postgresql.ENUM(name="trip_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="booking_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="user_role").drop(bind, checkfirst=True)
